#include<stdio.h>
int main()
{
    int test,i,l,c,s,j,k,start=0,start1=0;
    scanf("%d",&test);
    for(i=0;i<test;i++)
    {
        scanf("%d",&l);
        scanf("%d",&c);
        scanf("%d",&s);
        for(k=0;k<(l*s+l+1);k++)
        {
            if(k%(s+1)==0)
            {
                if(start==0)
                start=1;
                else
                start=0;
                for(j=0;j<(c*s+c+1);j++)
                {
                    printf("*");
                }
            }
            else
            {
                for(j=0;j<(c*s+c+1);j++)
                { 
                    if(j%(s+1)==0)
                    {
                        printf("*");
                        //start=1;
                        if(j!=c*s+c)
                        {
                            if(start1==0)
                                start1=1;
                            else
                                start1=0;
                        }
                    }
                    else
                    {
                        //printf(" ");
                        if(start==1)
                        {
                            if(start1==1)
                            {
                                if(k%(s+1)==j%(s+1))
                                {
                                    printf("\\");
                                }
                                else
                                {
                                    printf(".");
                                }
                            }
                            else
                            {
                                //if((k%(s+1))+(j%(s+1))==(s+1))
                                if(k%(s+1)==j%(s+1))
                                {
                                    printf("\\");
                                }
                                else
                                {
                                    printf(".");
                                }
                            }
                        }
                        else
                        {
                            if(start1==1)
                            {
                                if((k%(s+1))+(j%(s+1))==(s+1))
                                {
                                    printf("/");
                                }
                                else
                                {
                                    printf(".");
                                }
                            }
                            else
                            {
                                //if(k%(s+1)==j%(s+1))
                                if((k%(s+1))+(j%(s+1))==(s+1))
                                {
                                    printf("/");
                                }
                                else
                                {
                                    printf(".");
                                }
                            }
                        }
                    }
                    //printf("casestar:%d start:%d",casestar,start);
                }
                printf(" ");
            }
            printf("\n");
        }
    }
    return 0;
}